<?php
$database = new Database();
$database->query("SELECT * from product where `user_id` = " . $_SESSION["id"] . " ORDER BY product_id DESC;")

?>
<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

	<!-- begin:: Content -->
	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid ">

		<div class="kt-portlet kt-portlet--mobile">
			<div class="kt-portlet__head kt-portlet__head--lg">
				<div class="kt-portlet__head-label">
					<span class="kt-portlet__head-icon">
						<i class="kt-font-brand flaticon2-line-chart"></i>
					</span>
					<h3 class="kt-portlet__head-title">
						Product
						<small>List All Products here</small>
					</h3>
				</div>
				<div class="kt-portlet__head-toolbar">
					<div class="kt-portlet__head-wrapper">
						<div class="kt-portlet__head-actions">
							<a id="new_product" href="#" class="btn btn-brand btn-elevate btn-icon-sm" data-toggle="modal" data-target="#addProductModal">
								<i class="la la-plus"></i>
								New Product
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="kt-portlet__body">

				<!--begin: Search Form -->
				<div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
					<div class="row align-items-center">
						<div class="col-xl-8 order-2 order-xl-1">
							<div class="row align-items-center">
								<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
									<div class="kt-input-icon kt-input-icon--left">
										<input type="text" class="form-control" placeholder="Search..." id="generalSearch">
										<span class="kt-input-icon__icon kt-input-icon__icon--left">
											<span><i class="la la-search"></i></span>
										</span>
									</div>
								</div>
								<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
									<div class="kt-form__group kt-form__group--inline">
										<div class="kt-form__label">
											<label>Status:</label>
										</div>
										<div class="kt-form__control">
											<select class="form-control bootstrap-select" id="kt_form_status">
												<option value="">All</option>
												<option value="1">Enable</option>
												<option value="2">Disable</option>
											</select>
										</div>
									</div>
									<!-- </div>
													<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
														<div class="kt-form__group kt-form__group--inline">
															<div class="kt-form__label">
																<label>Type:</label>
															</div>
															<div class="kt-form__control">
																<select class="form-control bootstrap-select" id="kt_form_type">
																	<option value="">All</option>
																	<option value="1">Online</option>
																	<option value="2">Retail</option>
																	<option value="3">Direct</option>
																</select>
															</div>
														</div>
													</div> -->
								</div>
							</div>
						</div>
					</div>

					<!--end: Search Form -->
				</div>
				<div class="kt-portlet__body kt-portlet__body--fit">

					<!--begin: Datatable -->
					<table class="kt-datatable" id="html_table" width="100%">
						<thead>
							<tr>
								<th title="Field #1">ID</th>
								<!-- <th title="Field #2">Image</th> -->
								<th title="Field #3">Name</th>
								<!-- <th title="Field #4">Description</th> -->
								<th title="Field #5">Size</th>
								<th title="Field #6">Price</th>
								<th title="Field #7">Date</th>
								<th title="Field #8">Status</th>
								<th title="Field #9">Actions</th>
								<!-- <th title="Field #8">Type</th> -->
							</tr>
						</thead>
						<tbody>
							<?php
							while ($database->next()) {
							?>
								<tr>
									<td><?= $database->get("product_id") ?></td>
									<!-- <td> </td> -->
									<td><div class="kt-user-card-v2">
											<div class="kt-user-card-v2__pic ">
												<img src="<?= ($database->get("product_image") != null) ? $database->get("product_image") : '../assets/media/products/default.png' ?>" alt="Pic">
											</div>
											<div class="kt-user-card-v2__details">
												<span class="kt-user-card-v2__name"><?= $database->get("product_name") ?></span>
												<a href="#" class="kt-user-card-v2__email kt-link"><?= $database->get("product_description") ?></a>
											</div>
										</div></td>
									<!-- <td></td> -->
									<td><?= $database->get("product_size") ?></td>
									<td>$<?= $database->get("product_price") ?></td>
									<td><?= $database->get("product_date") ?></td>
									<td align="right"> <?= $database->get("product_status") ?> </td>
									<td data-field="Actions" data-autohide-disabled="false" class="kt-datatable__cell">
										<span style="overflow: visible; position: relative; width: 110px;">
											<div class="dropdown"> 
												<a data-toggle="dropdown" class="btn btn-sm btn-clean btn-icon btn-icon-md"> <i class="la la-cog"></i> </a>
												<div class="dropdown-menu dropdown-menu-right"> 
													<a class="dropdown-item"><i class="la la-leaf"></i> <?= $database->get("product_status") == 1 ? "Disable" : "Enable" ?> Product</a> 
												</div>
											</div>
											<a title="Edit details"  onclick="edit_called(this)" data-toggle="modal" data-target="#addProductModal" class="btn btn-sm btn-clean btn-icon btn-icon-md">
												<i class="la la-edit"></i>
											</a>
											<a title="Delete" class="btn btn-sm btn-clean btn-icon btn-icon-md">
												<i class="la la-trash"></i>
											</a>
										</span>
									</td>
									<!-- <td align="right">3</td> -->
								</tr>
							<?php
							}
							?>
						</tbody>
					</table>

					<!--end: Datatable -->
				</div>
			</div>
		</div>

		<!-- end:: Content -->
	</div>
	<div class="modal fade" id="addProductModal" tabindex="-1" role="dialog" aria-labelledby="addProductModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="addProductModalLabel">Product</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					</button>
				</div>
				<form action="" id="product_form">
					<input type="hidden" name="" value="1" id="form_manager">
					<div class="modal-body">
						<div class="kt-form kt-form--label-right">
							<div class="kt-form__body">
								<div class="kt-section kt-section--first">
									<div class="kt-section__body">
										<div class="form-group row">
											<label class="col-xl-3 col-lg-3 col-form-label">Image</label>
											<div class="col-lg-9 col-xl-6">
												<div class="kt-avatar kt-avatar--outline kt-avatar--circle-" id="kt_user_edit_avatar">
													<div class="kt-avatar__holder" style="background-image: url('../assets/media/products/default.png');"></div>
													<label class="kt-avatar__upload" data-toggle="kt-tooltip" title="" data-original-title="Change avatar">
														<i class="fa fa-pen"></i>
														<input type="file" name="image" accept="image/*">
													</label>
													<span class="kt-avatar__cancel" data-toggle="kt-tooltip" title="" data-original-title="Cancel avatar">
														<i class="fa fa-times"></i>
													</span>
												</div>
											</div>
										</div>
										<div class="form-group row">
											<label class="col-xl-3 col-lg-3 col-form-label">Name</label>
											<div class="col-lg-9 col-xl-6">
												<input class="form-control" type="text" placeholder="Enter Product Name" name="name">
											</div>
										</div>
										<div class="form-group row">
											<label class="col-xl-3 col-lg-3 col-form-label">Description</label>
											<div class="col-lg-9 col-xl-6">
												<textarea class="form-control" name="description" id="exampleTextarea" rows="2"></textarea>
											</div>
										</div>
										<div class="form-group row">
											<label class="col-xl-3 col-lg-3 col-form-label">Size</label>
											<div class="col-lg-9 col-xl-6">
												<input class="form-control" type="text" name="size" placeholder="small, medium, large, extra large">
											</div>
										</div>
										<div class="form-group row">
											<label class="col-xl-3 col-lg-3 col-form-label">price</label>
											<div class="col-lg-9 col-xl-6">
												<input class="form-control" name="price" type="text" placeholder="120.3">
											</div>
										</div>
										<div class="form-group row">
											<label class="col-xl-3 col-lg-3 col-form-label">Quantity</label>
											<div class="col-lg-9 col-xl-6">
												<input class="form-control" name="qty" type="number" placeholder="20">
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-brand btn-elevate kt-login__btn-primary" id="kt_product_submit">Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>