<!DOCTYPE html>

<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 4 & Angular 8
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<html lang="en">

	<!-- begin::Head -->
	<head>
		<base href="">
		<meta charset="utf-8" />
		<title>Fanatics | Dashboard</title>
		<meta name="description" content="Updates and statistics">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!--begin::Fonts -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">

		<!--end::Fonts -->

		<!--begin::Page Vendors Styles(used by this page) -->

		<!--end::Page Vendors Styles -->

		<!--begin::Global Theme Styles(used by all pages) -->

		<!--begin:: Vendor Plugins -->
		<link href="assets/plugins/general/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/tether/dist/css/tether.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-timepicker/css/bootstrap-timepicker.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-select/dist/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/select2/dist/css/select2.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/ion-rangeslider/css/ion.rangeSlider.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/nouislider/distribute/nouislider.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/owl.carousel/dist/assets/owl.carousel.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/owl.carousel/dist/assets/owl.theme.default.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/dropzone/dist/dropzone.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/quill/dist/quill.snow.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/summernote/dist/summernote.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/animate.css/animate.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/toastr/build/toastr.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/dual-listbox/dist/dual-listbox.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/morris.js/morris.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/sweetalert2/dist/sweetalert2.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/socicon/css/socicon.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/plugins/line-awesome/css/line-awesome.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/plugins/flaticon/flaticon.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/plugins/flaticon2/flaticon.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/general/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css" />

		<!--end:: Vendor Plugins -->
		<link href="assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

		<!--begin:: Vendor Plugins for custom pages -->
		<link href="assets/plugins/custom/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/@fullcalendar/core/main.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/@fullcalendar/daygrid/main.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/@fullcalendar/list/main.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/@fullcalendar/timegrid/main.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-autofill-bs4/css/autoFill.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-colreorder-bs4/css/colReorder.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-fixedheader-bs4/css/fixedHeader.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-keytable-bs4/css/keyTable.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-rowgroup-bs4/css/rowGroup.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-rowreorder-bs4/css/rowReorder.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-scroller-bs4/css/scroller.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/datatables.net-select-bs4/css/select.bootstrap4.min.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/jstree/dist/themes/default/style.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/jqvmap/dist/jqvmap.css" rel="stylesheet" type="text/css" />
		<link href="assets/plugins/custom/uppy/dist/uppy.min.css" rel="stylesheet" type="text/css" />

		<!--end:: Vendor Plugins for custom pages -->

		<!--end::Global Theme Styles -->

		<!--begin::Layout Skins(used by all pages) -->
		<link href="assets/css/skins/header/base/light.css" rel="stylesheet" type="text/css" />
		<link href="assets/css/skins/header/menu/light.css" rel="stylesheet" type="text/css" />
		<link href="assets/css/skins/brand/dark.css" rel="stylesheet" type="text/css" />
		<link href="assets/css/skins/aside/dark.css" rel="stylesheet" type="text/css" />

		<!--end::Layout Skins -->
		<link rel="shortcut icon" href="assets/media/logos/favicon.ico" />
	</head>

	<!-- end::Head -->

	<!-- begin::Body -->
	<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--fixed kt-subheader--solid kt-aside--enabled kt-aside--fixed">

		<!-- begin:: Page -->

		<!-- begin:: Header Mobile -->
		<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
			<div class="kt-header-mobile__logo">
				<a href="index.html">
					<img alt="Logo" src="assets/media/logos/logo-light.png" />
				</a>
			</div>
			<div class="kt-header-mobile__toolbar">
				<button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
				<button class="kt-header-mobile__toggler" id="kt_header_mobile_toggler"><span></span></button>
				<button class="kt-header-mobile__topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
			</div>
		</div>

		<!-- end:: Header Mobile -->
		<div class="kt-grid kt-grid--hor kt-grid--root">
			<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

				<!-- begin:: Aside -->

				<!-- Uncomment this to display the close button of the panel
<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
-->
				<div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

					<!-- begin:: Aside -->
					<div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
						<div class="kt-aside__brand-logo">
							<a href="index.html">
								<img alt="Logo" src="assets/media/logos/fanatics-logo.png" width="160"/>
							</a>
						</div>
						<div class="kt-aside__brand-tools">
							<button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
								<span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
										<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
											<polygon points="0 0 24 0 24 24 0 24" />
											<path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z" fill="#000000" fill-rule="nonzero" transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) " />
											<path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) " />
										</g>
									</svg></span>
								<span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
										<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
											<polygon points="0 0 24 0 24 24 0 24" />
											<path d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z" fill="#000000" fill-rule="nonzero" />
											<path d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) " />
										</g>
									</svg></span>
							</button>

							<!--
			<button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>
			-->
						</div>
					</div>

					<!-- end:: Aside -->

					<!-- begin:: Aside Menu -->
					<div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
						<div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500">
							<ul class="kt-menu__nav ">
								<li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true"><a href="index.html" class="kt-menu__link "><span class="kt-menu__link-icon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
												<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
													<polygon points="0 0 24 0 24 24 0 24" />
													<path d="M12.9336061,16.072447 L19.36,10.9564761 L19.5181585,10.8312381 C20.1676248,10.3169571 20.2772143,9.3735535 19.7629333,8.72408713 C19.6917232,8.63415859 19.6104327,8.55269514 19.5206557,8.48129411 L12.9336854,3.24257445 C12.3871201,2.80788259 11.6128799,2.80788259 11.0663146,3.24257445 L4.47482784,8.48488609 C3.82645598,9.00054628 3.71887192,9.94418071 4.23453211,10.5925526 C4.30500305,10.6811601 4.38527899,10.7615046 4.47382636,10.8320511 L4.63,10.9564761 L11.0659024,16.0730648 C11.6126744,16.5077525 12.3871218,16.5074963 12.9336061,16.072447 Z" fill="#000000" fill-rule="nonzero" />
													<path d="M11.0563554,18.6706981 L5.33593024,14.122919 C4.94553994,13.8125559 4.37746707,13.8774308 4.06710397,14.2678211 C4.06471678,14.2708238 4.06234874,14.2738418 4.06,14.2768747 L4.06,14.2768747 C3.75257288,14.6738539 3.82516916,15.244888 4.22214834,15.5523151 C4.22358765,15.5534297 4.2250303,15.55454 4.22647627,15.555646 L11.0872776,20.8031356 C11.6250734,21.2144692 12.371757,21.2145375 12.909628,20.8033023 L19.7677785,15.559828 C20.1693192,15.2528257 20.2459576,14.6784381 19.9389553,14.2768974 C19.9376429,14.2751809 19.9363245,14.2734691 19.935,14.2717619 L19.935,14.2717619 C19.6266937,13.8743807 19.0546209,13.8021712 18.6572397,14.1104775 C18.654352,14.112718 18.6514778,14.1149757 18.6486172,14.1172508 L12.9235044,18.6705218 C12.377022,19.1051477 11.6029199,19.1052208 11.0563554,18.6706981 Z" fill="#000000" opacity="0.3" />
												</g>
											</svg></span><span class="kt-menu__link-text">Product</span></a></li>
								
							</ul>
						</div>
					</div>

					<!-- end:: Aside Menu -->
				</div>

				<!-- end:: Aside -->
				<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

					<!-- begin:: Header -->
					<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">

						<!-- begin:: Header Menu -->

						<!-- Uncomment this to display the close button of the panel
<button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
-->
						<div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
							
						</div>

						<!-- end:: Header Menu -->

						<!-- begin:: Header Topbar -->
						<div class="kt-header__topbar">

						

							



							<!--end: Language bar -->

							<!--begin: User Bar -->
							<div class="kt-header__topbar-item kt-header__topbar-item--user">
								<div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px,0px">
									<div class="kt-header__topbar-user">
										<span class="kt-header__topbar-welcome kt-hidden-mobile">Hi,</span>
										<span class="kt-header__topbar-username kt-hidden-mobile"><?= isset($_SESSION['username']) ? ucfirst( explode("/( )/",$_SESSION['username'],1)[0] ) : "Guest" ?></span>
										<img class="kt-hidden" alt="Pic" src="assets/media/users/300_25.jpg" />

										<!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
										<span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold"><?= isset($_SESSION['username']) ? ucfirst( substr($_SESSION['username'],0,1) ) : "G" ?></span>
									</div>
								</div>
								<div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-xl">

									<!--begin: Head -->
									<div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x" style="background-image: url(assets/media/misc/bg-1.jpg)">
										<div class="kt-user-card__avatar">
											<img class="kt-hidden" alt="Pic" src="assets/media/users/300_25.jpg" />

											<!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
											<span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success"><?= isset($_SESSION['username']) ? ucfirst( substr($_SESSION['username'],0,1)) : "G" ?></span>
										</div>
										<div class="kt-user-card__name">
										<?= isset($_SESSION['username']) ? ucwords($_SESSION['username']) : "Guest User" ?>
										</div>
										<div class="kt-user-card__badge">
											<span class="btn btn-success btn-sm btn-bold btn-font-md">23 messages</span>
										</div>
									</div>

									<!--end: Head -->

									
									<!--begin: Navigation -->
									<div class="kt-notification">
									<?php
										if(isset($_SESSION['username']))
										{
									?>
										<a href="custom/apps/user/profile-1/personal-information.html" class="kt-notification__item">
											<div class="kt-notification__item-icon">
												<i class="flaticon2-calendar-3 kt-font-success"></i>
											</div>
											<div class="kt-notification__item-details">
												<div class="kt-notification__item-title kt-font-bold">
													My Profile
												</div>
												<div class="kt-notification__item-time">
													Account settings and more
												</div>
											</div>
										</a>
										<div class="kt-notification__custom kt-space-between">
											<a href="index.php?logout=true"  class="btn btn-label btn-label-brand btn-sm btn-bold">Sign Out</a>
									<?php
										}
										else
										{
									?>
										<div class="kt-notification__custom kt-space-between">
											<a href="login.php"  class="btn btn-label btn-label-brand btn-sm btn-bold">Sign In</a>
									<?php
										}
									?>	
										</div>
									</div>

									<!--end: Navigation -->
								</div>
							</div>

							<!--end: User Bar -->
						</div>

						<!-- end:: Header Topbar -->
					</div>

					<!-- end:: Header -->
					<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

						<!-- begin:: Content -->
						<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid ">
							
							<div class="kt-portlet kt-portlet--mobile">
								<div class="kt-portlet__head kt-portlet__head--lg">
									<div class="kt-portlet__head-label">
										<span class="kt-portlet__head-icon">
											<i class="kt-font-brand flaticon2-line-chart"></i>
										</span>
										<h3 class="kt-portlet__head-title">
											Product
											<small>List All Products here</small>
										</h3>
									</div>
									<div class="kt-portlet__head-toolbar">
										<div class="kt-portlet__head-wrapper">
											<div class="kt-portlet__head-actions">
												<a href="#" class="btn btn-brand btn-elevate btn-icon-sm">
													<i class="la la-plus"></i>
													New Product
												</a>
											</div>
										</div>
									</div>
								</div>
								<div class="kt-portlet__body">

									<!--begin: Search Form -->
									<div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
										<div class="row align-items-center">
											<div class="col-xl-8 order-2 order-xl-1">
												<div class="row align-items-center">
													<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
														<div class="kt-input-icon kt-input-icon--left">
															<input type="text" class="form-control" placeholder="Search..." id="generalSearch">
															<span class="kt-input-icon__icon kt-input-icon__icon--left">
																<span><i class="la la-search"></i></span>
															</span>
														</div>
													</div>
													<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
														<div class="kt-form__group kt-form__group--inline">
															<div class="kt-form__label">
																<label>Status:</label>
															</div>
															<div class="kt-form__control">
																<select class="form-control bootstrap-select" id="kt_form_status">
																	<option value="">All</option>
																	<option value="1">Pending</option>
																	<option value="2">Delivered</option>
																	<option value="3">Canceled</option>
																	<option value="4">Success</option>
																	<option value="5">Info</option>
																	<option value="6">Danger</option>
																</select>
															</div>
														</div>
													</div>
													<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
														<div class="kt-form__group kt-form__group--inline">
															<div class="kt-form__label">
																<label>Type:</label>
															</div>
															<div class="kt-form__control">
																<select class="form-control bootstrap-select" id="kt_form_type">
																	<option value="">All</option>
																	<option value="1">Online</option>
																	<option value="2">Retail</option>
																	<option value="3">Direct</option>
																</select>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="col-xl-4 order-1 order-xl-2 kt-align-right">
												<a href="#" class="btn btn-default kt-hidden">
													<i class="la la-cart-plus"></i> New Order
												</a>
												<div class="kt-separator kt-separator--border-dashed kt-separator--space-lg d-xl-none"></div>
											</div>
										</div>
									</div>

									<!--end: Search Form -->
								</div>
								<div class="kt-portlet__body kt-portlet__body--fit">

									<!--begin: Datatable -->
									<table class="kt-datatable" id="html_table" width="100%">
										<thead>
											<tr>
												<th title="Field #1">Order ID</th>
												<th title="Field #2">Car Make</th>
												<th title="Field #3">Car Model</th>
												<th title="Field #4">Color</th>
												<th title="Field #5">Deposit Paid</th>
												<th title="Field #6">Order Date</th>
												<th title="Field #7">Status</th>
												<th title="Field #8">Type</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>0006-3629</td>
												<td>Land Rover</td>
												<td>Range Rover</td>
												<td>Orange</td>
												<td>$22672.60</td>
												<td>2016-11-28</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>66403-315</td>
												<td>GMC</td>
												<td>Jimmy</td>
												<td>Goldenrod</td>
												<td>$55141.29</td>
												<td>2017-04-29</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>54868-5055</td>
												<td>Ford</td>
												<td>Club Wagon</td>
												<td>Goldenrod</td>
												<td>$70991.52</td>
												<td>2017-03-16</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>44924-112</td>
												<td>GMC</td>
												<td>Envoy</td>
												<td>Indigo</td>
												<td>$42615.31</td>
												<td>2016-09-04</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>0378-0357</td>
												<td>Saab</td>
												<td>9-5</td>
												<td>Teal</td>
												<td>$74919.63</td>
												<td>2017-09-21</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0363-0590</td>
												<td>Suzuki</td>
												<td>Grand Vitara</td>
												<td>Crimson</td>
												<td>$72908.80</td>
												<td>2017-04-03</td>
												<td align="right">5</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>35356-778</td>
												<td>Dodge</td>
												<td>Ram 2500</td>
												<td>Goldenrod</td>
												<td>$13569.00</td>
												<td>2016-03-22</td>
												<td align="right">5</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>48951-3040</td>
												<td>Mitsubishi</td>
												<td>Eclipse</td>
												<td>Aquamarine</td>
												<td>$22471.73</td>
												<td>2016-04-17</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0487-9801</td>
												<td>Pontiac</td>
												<td>GTO</td>
												<td>Green</td>
												<td>$43149.39</td>
												<td>2016-05-27</td>
												<td align="right">4</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>54753-003</td>
												<td>Audi</td>
												<td>S4</td>
												<td>Turquoise</td>
												<td>$39286.74</td>
												<td>2016-07-23</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>34460-6006</td>
												<td>Audi</td>
												<td>Allroad</td>
												<td>Mauv</td>
												<td>$47394.02</td>
												<td>2016-06-21</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>62802-106</td>
												<td>GMC</td>
												<td>Sierra 1500</td>
												<td>Teal</td>
												<td>$47469.52</td>
												<td>2016-05-06</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>43269-664</td>
												<td>Buick</td>
												<td>Terraza</td>
												<td>Orange</td>
												<td>$94980.73</td>
												<td>2017-08-17</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>65862-602</td>
												<td>Ford</td>
												<td>Crown Victoria</td>
												<td>Green</td>
												<td>$36215.40</td>
												<td>2016-09-01</td>
												<td align="right">6</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>18527-119</td>
												<td>Toyota</td>
												<td>Sequoia</td>
												<td>Mauv</td>
												<td>$46000.92</td>
												<td>2016-05-17</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>55910-994</td>
												<td>Mercedes-Benz</td>
												<td>C-Class</td>
												<td>Turquoise</td>
												<td>$76272.22</td>
												<td>2016-01-10</td>
												<td align="right">6</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>49349-441</td>
												<td>Audi</td>
												<td>Cabriolet</td>
												<td>Red</td>
												<td>$33624.99</td>
												<td>2017-07-31</td>
												<td align="right">2</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0573-0232</td>
												<td>Hyundai</td>
												<td>Tucson</td>
												<td>Puce</td>
												<td>$97796.98</td>
												<td>2017-02-10</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>49643-326</td>
												<td>Lexus</td>
												<td>IS</td>
												<td>Pink</td>
												<td>$88864.37</td>
												<td>2016-06-01</td>
												<td align="right">5</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0944-2627</td>
												<td>Audi</td>
												<td>S4</td>
												<td>Maroon</td>
												<td>$25024.94</td>
												<td>2016-12-16</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>33992-1210</td>
												<td>BMW</td>
												<td>7 Series</td>
												<td>Green</td>
												<td>$89144.60</td>
												<td>2017-06-02</td>
												<td align="right">4</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>53808-0478</td>
												<td>Volkswagen</td>
												<td>Eurovan</td>
												<td>Red</td>
												<td>$69113.93</td>
												<td>2017-12-17</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>51531-0332</td>
												<td>Mitsubishi</td>
												<td>Tredia</td>
												<td>Aquamarine</td>
												<td>$28062.46</td>
												<td>2016-03-14</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>49852-181</td>
												<td>Ford</td>
												<td>Thunderbird</td>
												<td>Green</td>
												<td>$75325.45</td>
												<td>2016-12-12</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>49614-133</td>
												<td>Jeep</td>
												<td>Grand Cherokee</td>
												<td>Mauv</td>
												<td>$45865.14</td>
												<td>2017-01-11</td>
												<td align="right">2</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0264-1800</td>
												<td>Hyundai</td>
												<td>XG350</td>
												<td>Khaki</td>
												<td>$82969.08</td>
												<td>2017-10-27</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>36987-2784</td>
												<td>Lexus</td>
												<td>LX</td>
												<td>Puce</td>
												<td>$50958.79</td>
												<td>2016-09-20</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>43319-050</td>
												<td>Lexus</td>
												<td>GS</td>
												<td>Orange</td>
												<td>$13672.91</td>
												<td>2017-11-23</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>33261-026</td>
												<td>Chevrolet</td>
												<td>SSR</td>
												<td>Teal</td>
												<td>$25036.57</td>
												<td>2017-10-28</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>60505-0381</td>
												<td>Chrysler</td>
												<td>New Yorker</td>
												<td>Yellow</td>
												<td>$35660.00</td>
												<td>2017-01-21</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>29500-2438</td>
												<td>Saturn</td>
												<td>S-Series</td>
												<td>Khaki</td>
												<td>$79451.58</td>
												<td>2017-09-24</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>21695-901</td>
												<td>Volvo</td>
												<td>XC70</td>
												<td>Goldenrod</td>
												<td>$34678.63</td>
												<td>2016-12-26</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>48951-7062</td>
												<td>Mercedes-Benz</td>
												<td>CLm-Class</td>
												<td>Yellow</td>
												<td>$86018.69</td>
												<td>2016-07-16</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>57520-0214</td>
												<td>Suzuki</td>
												<td>Grand Vitara</td>
												<td>Orange</td>
												<td>$48087.48</td>
												<td>2017-06-13</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0143-1240</td>
												<td>Mazda</td>
												<td>Miata MX-5</td>
												<td>Green</td>
												<td>$72500.87</td>
												<td>2017-04-26</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>34666-091</td>
												<td>Cadillac</td>
												<td>DeVille</td>
												<td>Goldenrod</td>
												<td>$54846.02</td>
												<td>2016-12-29</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>65044-1300</td>
												<td>Subaru</td>
												<td>Impreza</td>
												<td>Yellow</td>
												<td>$64200.42</td>
												<td>2016-07-08</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>54868-6195</td>
												<td>Dodge</td>
												<td>Caravan</td>
												<td>Yellow</td>
												<td>$35142.11</td>
												<td>2016-11-25</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>36987-1837</td>
												<td>Volkswagen</td>
												<td>New Beetle</td>
												<td>Maroon</td>
												<td>$44383.94</td>
												<td>2016-03-29</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>50580-669</td>
												<td>Lotus</td>
												<td>Exige</td>
												<td>Orange</td>
												<td>$73977.83</td>
												<td>2017-10-29</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>65044-4703</td>
												<td>Toyota</td>
												<td>Solara</td>
												<td>Fuscia</td>
												<td>$23480.69</td>
												<td>2016-12-03</td>
												<td align="right">2</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>50730-8628</td>
												<td>Suzuki</td>
												<td>SX4</td>
												<td>Green</td>
												<td>$77498.41</td>
												<td>2017-11-14</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>64896-672</td>
												<td>Volvo</td>
												<td>940</td>
												<td>Violet</td>
												<td>$85460.14</td>
												<td>2016-08-09</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>17772-121</td>
												<td>Dodge</td>
												<td>Grand Caravan</td>
												<td>Crimson</td>
												<td>$70315.20</td>
												<td>2017-06-07</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>57520-1032</td>
												<td>Chevrolet</td>
												<td>Express 3500</td>
												<td>Yellow</td>
												<td>$35840.40</td>
												<td>2016-10-26</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>62206-4760</td>
												<td>Dodge</td>
												<td>Viper</td>
												<td>Aquamarine</td>
												<td>$87294.01</td>
												<td>2016-09-06</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>49349-123</td>
												<td>BMW</td>
												<td>X3</td>
												<td>Khaki</td>
												<td>$20584.12</td>
												<td>2016-09-26</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>49726-026</td>
												<td>Hummer</td>
												<td>H2</td>
												<td>Pink</td>
												<td>$99359.45</td>
												<td>2016-03-22</td>
												<td align="right">6</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0378-6540</td>
												<td>Bentley</td>
												<td>Continental Flying Spur</td>
												<td>Fuscia</td>
												<td>$31824.99</td>
												<td>2017-08-28</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>65977-5037</td>
												<td>Chevrolet</td>
												<td>3500</td>
												<td>Violet</td>
												<td>$11410.89</td>
												<td>2017-10-17</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>10337-061</td>
												<td>Mercury</td>
												<td>Grand Marquis</td>
												<td>Goldenrod</td>
												<td>$78350.91</td>
												<td>2017-08-10</td>
												<td align="right">6</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0407-1401</td>
												<td>GMC</td>
												<td>Sonoma Club Coupe</td>
												<td>Goldenrod</td>
												<td>$58769.66</td>
												<td>2017-11-24</td>
												<td align="right">5</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>55315-531</td>
												<td>Chrysler</td>
												<td>Town &amp; Country</td>
												<td>Pink</td>
												<td>$68769.98</td>
												<td>2016-10-04</td>
												<td align="right">5</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>13107-031</td>
												<td>Mazda</td>
												<td>Mazda6</td>
												<td>Teal</td>
												<td>$98059.90</td>
												<td>2017-08-27</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>52584-978</td>
												<td>Cadillac</td>
												<td>CTS</td>
												<td>Teal</td>
												<td>$92723.12</td>
												<td>2016-10-21</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>65044-1451</td>
												<td>Volkswagen</td>
												<td>Touareg</td>
												<td>Aquamarine</td>
												<td>$14614.66</td>
												<td>2017-08-18</td>
												<td align="right">2</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>57297-201</td>
												<td>Chrysler</td>
												<td>300C</td>
												<td>Indigo</td>
												<td>$88757.67</td>
												<td>2016-09-24</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>55154-6256</td>
												<td>GMC</td>
												<td>Yukon XL 1500</td>
												<td>Goldenrod</td>
												<td>$38738.02</td>
												<td>2016-04-21</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>50169-0007</td>
												<td>Honda</td>
												<td>Prelude</td>
												<td>Indigo</td>
												<td>$24546.46</td>
												<td>2017-09-23</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>61786-001</td>
												<td>Toyota</td>
												<td>Avalon</td>
												<td>Turquoise</td>
												<td>$71384.57</td>
												<td>2017-11-27</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>58232-0527</td>
												<td>Cadillac</td>
												<td>Catera</td>
												<td>Khaki</td>
												<td>$42349.91</td>
												<td>2016-08-18</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>0075-0626</td>
												<td>Lamborghini</td>
												<td>Diablo</td>
												<td>Maroon</td>
												<td>$19993.34</td>
												<td>2017-02-28</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>52584-928</td>
												<td>Mitsubishi</td>
												<td>Galant</td>
												<td>Indigo</td>
												<td>$27921.88</td>
												<td>2017-05-11</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>63868-106</td>
												<td>Isuzu</td>
												<td>Trooper</td>
												<td>Aquamarine</td>
												<td>$95391.97</td>
												<td>2016-10-21</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>54868-5918</td>
												<td>Daewoo</td>
												<td>Leganza</td>
												<td>Purple</td>
												<td>$99652.50</td>
												<td>2016-09-24</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>62097-0003</td>
												<td>BMW</td>
												<td>X5</td>
												<td>Orange</td>
												<td>$98667.84</td>
												<td>2016-05-07</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>49349-222</td>
												<td>Land Rover</td>
												<td>Discovery</td>
												<td>Blue</td>
												<td>$29519.94</td>
												<td>2017-05-14</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>64725-2957</td>
												<td>Honda</td>
												<td>Odyssey</td>
												<td>Teal</td>
												<td>$83826.93</td>
												<td>2017-09-13</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>59088-962</td>
												<td>Dodge</td>
												<td>Journey</td>
												<td>Goldenrod</td>
												<td>$90702.32</td>
												<td>2017-02-15</td>
												<td align="right">5</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>60681-1804</td>
												<td>Pontiac</td>
												<td>Firefly</td>
												<td>Goldenrod</td>
												<td>$50858.26</td>
												<td>2017-11-28</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>58668-3251</td>
												<td>Nissan</td>
												<td>Murano</td>
												<td>Yellow</td>
												<td>$43973.10</td>
												<td>2016-01-27</td>
												<td align="right">2</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>16590-870</td>
												<td>Toyota</td>
												<td>Solara</td>
												<td>Yellow</td>
												<td>$79845.88</td>
												<td>2016-09-04</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0159-2200</td>
												<td>Honda</td>
												<td>Prelude</td>
												<td>Yellow</td>
												<td>$21019.04</td>
												<td>2016-07-06</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>36987-2048</td>
												<td>Ford</td>
												<td>F350</td>
												<td>Violet</td>
												<td>$28398.23</td>
												<td>2016-09-09</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>66116-471</td>
												<td>GMC</td>
												<td>Vandura G2500</td>
												<td>Pink</td>
												<td>$41272.55</td>
												<td>2016-08-16</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>46122-194</td>
												<td>Buick</td>
												<td>Century</td>
												<td>Green</td>
												<td>$38542.57</td>
												<td>2017-04-08</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>60505-2665</td>
												<td>Ford</td>
												<td>E-Series</td>
												<td>Orange</td>
												<td>$17418.92</td>
												<td>2017-09-05</td>
												<td align="right">4</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>49999-958</td>
												<td>Maserati</td>
												<td>Coupe</td>
												<td>Yellow</td>
												<td>$82070.50</td>
												<td>2017-11-21</td>
												<td align="right">5</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>43353-763</td>
												<td>Porsche</td>
												<td>Carrera GT</td>
												<td>Yellow</td>
												<td>$98546.87</td>
												<td>2017-03-20</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>55714-4528</td>
												<td>Buick</td>
												<td>LaCrosse</td>
												<td>Green</td>
												<td>$13443.37</td>
												<td>2016-08-29</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>62037-560</td>
												<td>Chevrolet</td>
												<td>Equinox</td>
												<td>Green</td>
												<td>$46644.32</td>
												<td>2016-09-27</td>
												<td align="right">1</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>36987-2934</td>
												<td>Pontiac</td>
												<td>Grand Am</td>
												<td>Teal</td>
												<td>$46571.89</td>
												<td>2016-10-30</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>65044-5054</td>
												<td>Toyota</td>
												<td>Camry</td>
												<td>Turquoise</td>
												<td>$73062.72</td>
												<td>2016-02-19</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>69015-110</td>
												<td>Ford</td>
												<td>F-Series</td>
												<td>Goldenrod</td>
												<td>$58325.82</td>
												<td>2017-12-10</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>63868-172</td>
												<td>Maybach</td>
												<td>57</td>
												<td>Goldenrod</td>
												<td>$27746.98</td>
												<td>2016-09-16</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>11673-136</td>
												<td>Isuzu</td>
												<td>Hombre</td>
												<td>Pink</td>
												<td>$25289.00</td>
												<td>2016-06-08</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>68391-319</td>
												<td>Mercury</td>
												<td>Mystique</td>
												<td>Maroon</td>
												<td>$94443.18</td>
												<td>2017-01-19</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>51334-289</td>
												<td>Toyota</td>
												<td>Camry</td>
												<td>Crimson</td>
												<td>$54495.33</td>
												<td>2016-08-26</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>51531-4189</td>
												<td>Mazda</td>
												<td>Mazda2</td>
												<td>Orange</td>
												<td>$61069.76</td>
												<td>2016-07-17</td>
												<td align="right">2</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>76260-105</td>
												<td>Buick</td>
												<td>Riviera</td>
												<td>Aquamarine</td>
												<td>$73556.08</td>
												<td>2017-02-09</td>
												<td align="right">6</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>35000-120</td>
												<td>Chevrolet</td>
												<td>Citation</td>
												<td>Teal</td>
												<td>$93666.82</td>
												<td>2016-08-09</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>16714-271</td>
												<td>Ford</td>
												<td>Edge</td>
												<td>Orange</td>
												<td>$88055.07</td>
												<td>2017-08-23</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>76214-032</td>
												<td>Chrysler</td>
												<td>Pacifica</td>
												<td>Orange</td>
												<td>$90127.90</td>
												<td>2016-12-20</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>36987-2910</td>
												<td>Ford</td>
												<td>Escort</td>
												<td>Blue</td>
												<td>$31400.58</td>
												<td>2017-05-24</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>52584-631</td>
												<td>Dodge</td>
												<td>Dakota</td>
												<td>Purple</td>
												<td>$11543.58</td>
												<td>2016-12-03</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>36987-2632</td>
												<td>BMW</td>
												<td>530</td>
												<td>Purple</td>
												<td>$88325.98</td>
												<td>2016-06-26</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>50436-0127</td>
												<td>Buick</td>
												<td>LeSabre</td>
												<td>Fuscia</td>
												<td>$74403.19</td>
												<td>2016-07-30</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>50227-0511</td>
												<td>Chrysler</td>
												<td>Town &amp; Country</td>
												<td>Khaki</td>
												<td>$70358.02</td>
												<td>2016-02-22</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>51079-201</td>
												<td>Chevrolet</td>
												<td>Suburban 2500</td>
												<td>Maroon</td>
												<td>$50056.31</td>
												<td>2017-02-13</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>52456-018</td>
												<td>Porsche</td>
												<td>Cayman</td>
												<td>Maroon</td>
												<td>$54197.10</td>
												<td>2016-08-16</td>
												<td align="right">5</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>64942-1096</td>
												<td>Buick</td>
												<td>Electra</td>
												<td>Blue</td>
												<td>$10415.17</td>
												<td>2016-11-13</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>41250-994</td>
												<td>Mazda</td>
												<td>CX-7</td>
												<td>Pink</td>
												<td>$10107.79</td>
												<td>2016-01-02</td>
												<td align="right">6</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>55714-4405</td>
												<td>GMC</td>
												<td>Sonoma Club Coupe</td>
												<td>Crimson</td>
												<td>$72222.41</td>
												<td>2017-06-27</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>65862-460</td>
												<td>Ford</td>
												<td>E-Series</td>
												<td>Fuscia</td>
												<td>$33476.23</td>
												<td>2017-09-24</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>49852-164</td>
												<td>Toyota</td>
												<td>Tundra</td>
												<td>Puce</td>
												<td>$48155.56</td>
												<td>2017-03-09</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>17238-625</td>
												<td>Chevrolet</td>
												<td>Express 3500</td>
												<td>Crimson</td>
												<td>$57862.14</td>
												<td>2017-05-08</td>
												<td align="right">5</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0603-5449</td>
												<td>Land Rover</td>
												<td>Discovery Series II</td>
												<td>Purple</td>
												<td>$96847.00</td>
												<td>2017-06-24</td>
												<td align="right">4</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>0615-7757</td>
												<td>GMC</td>
												<td>Canyon</td>
												<td>Violet</td>
												<td>$98422.58</td>
												<td>2017-04-01</td>
												<td align="right">5</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>55264-021</td>
												<td>Mazda</td>
												<td>Mazda2</td>
												<td>Orange</td>
												<td>$20775.71</td>
												<td>2016-07-12</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>37808-961</td>
												<td>BMW</td>
												<td>M3</td>
												<td>Turquoise</td>
												<td>$11082.97</td>
												<td>2016-08-28</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>13107-119</td>
												<td>Dodge</td>
												<td>Ram 1500</td>
												<td>Orange</td>
												<td>$60145.34</td>
												<td>2017-10-19</td>
												<td align="right">6</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0268-0825</td>
												<td>Pontiac</td>
												<td>Grand Am</td>
												<td>Teal</td>
												<td>$64669.18</td>
												<td>2016-09-01</td>
												<td align="right">4</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>49348-047</td>
												<td>Chrysler</td>
												<td>Concorde</td>
												<td>Aquamarine</td>
												<td>$97877.37</td>
												<td>2016-10-13</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>58668-2691</td>
												<td>Porsche</td>
												<td>Panamera</td>
												<td>Maroon</td>
												<td>$47292.30</td>
												<td>2016-07-28</td>
												<td align="right">2</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>76168-009</td>
												<td>Chevrolet</td>
												<td>Tahoe</td>
												<td>Blue</td>
												<td>$82565.90</td>
												<td>2016-12-25</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>61941-0042</td>
												<td>Saturn</td>
												<td>VUE</td>
												<td>Crimson</td>
												<td>$92470.85</td>
												<td>2017-07-04</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>68428-047</td>
												<td>Kia</td>
												<td>Mentor</td>
												<td>Pink</td>
												<td>$20117.71</td>
												<td>2016-12-03</td>
												<td align="right">1</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>63214-102</td>
												<td>Chevrolet</td>
												<td>SSR</td>
												<td>Aquamarine</td>
												<td>$26697.23</td>
												<td>2016-06-28</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>64760-019</td>
												<td>Acura</td>
												<td>RL</td>
												<td>Crimson</td>
												<td>$26345.59</td>
												<td>2017-03-12</td>
												<td align="right">2</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>0378-6120</td>
												<td>Ford</td>
												<td>Econoline E350</td>
												<td>Turquoise</td>
												<td>$69574.74</td>
												<td>2016-04-21</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>10742-8597</td>
												<td>Kia</td>
												<td>Sorento</td>
												<td>Red</td>
												<td>$37394.42</td>
												<td>2017-05-11</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>60429-616</td>
												<td>GMC</td>
												<td>Yukon XL 2500</td>
												<td>Crimson</td>
												<td>$88038.77</td>
												<td>2017-10-14</td>
												<td align="right">5</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>68180-882</td>
												<td>Peugeot</td>
												<td>207</td>
												<td>Green</td>
												<td>$39938.08</td>
												<td>2017-11-09</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>55714-8001</td>
												<td>Lincoln</td>
												<td>LS</td>
												<td>Maroon</td>
												<td>$42066.09</td>
												<td>2016-05-12</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>42507-092</td>
												<td>Volkswagen</td>
												<td>Golf</td>
												<td>Purple</td>
												<td>$66158.98</td>
												<td>2017-10-11</td>
												<td align="right">4</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>58411-154</td>
												<td>Volvo</td>
												<td>S40</td>
												<td>Goldenrod</td>
												<td>$64825.98</td>
												<td>2017-12-02</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>46987-325</td>
												<td>Dodge</td>
												<td>Ram 3500</td>
												<td>Teal</td>
												<td>$42231.35</td>
												<td>2017-07-27</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>41520-958</td>
												<td>GMC</td>
												<td>Vandura G3500</td>
												<td>Yellow</td>
												<td>$64432.81</td>
												<td>2016-03-06</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0268-6317</td>
												<td>Infiniti</td>
												<td>FX</td>
												<td>Khaki</td>
												<td>$51991.87</td>
												<td>2016-07-19</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>53489-119</td>
												<td>Lexus</td>
												<td>GS</td>
												<td>Violet</td>
												<td>$16309.60</td>
												<td>2016-08-15</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>57261-786</td>
												<td>Subaru</td>
												<td>Alcyone SVX</td>
												<td>Red</td>
												<td>$58552.98</td>
												<td>2017-05-12</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>53329-822</td>
												<td>Chrysler</td>
												<td>PT Cruiser</td>
												<td>Violet</td>
												<td>$32530.48</td>
												<td>2016-04-05</td>
												<td align="right">6</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>0615-4545</td>
												<td>Dodge</td>
												<td>Ram Wagon B150</td>
												<td>Aquamarine</td>
												<td>$75206.57</td>
												<td>2016-08-12</td>
												<td align="right">2</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>66761-122</td>
												<td>Pontiac</td>
												<td>Trans Sport</td>
												<td>Mauv</td>
												<td>$28790.67</td>
												<td>2016-05-14</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>55289-241</td>
												<td>Chevrolet</td>
												<td>Silverado 1500</td>
												<td>Puce</td>
												<td>$68297.88</td>
												<td>2016-11-11</td>
												<td align="right">5</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>36987-1451</td>
												<td>Land Rover</td>
												<td>Defender 90</td>
												<td>Puce</td>
												<td>$30368.78</td>
												<td>2017-10-16</td>
												<td align="right">2</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0781-5805</td>
												<td>Mercury</td>
												<td>Sable</td>
												<td>Mauv</td>
												<td>$56681.99</td>
												<td>2016-11-16</td>
												<td align="right">3</td>
												<td align="right">1</td>
											</tr>
											<tr>
												<td>0409-4646</td>
												<td>Jeep</td>
												<td>Cherokee</td>
												<td>Red</td>
												<td>$26926.81</td>
												<td>2017-04-05</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>49643-017</td>
												<td>Chevrolet</td>
												<td>Express 3500</td>
												<td>Aquamarine</td>
												<td>$18094.00</td>
												<td>2016-07-23</td>
												<td align="right">4</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>50458-602</td>
												<td>Buick</td>
												<td>Skylark</td>
												<td>Indigo</td>
												<td>$85442.74</td>
												<td>2017-02-27</td>
												<td align="right">3</td>
												<td align="right">2</td>
											</tr>
											<tr>
												<td>51785-424</td>
												<td>Bentley</td>
												<td>Continental</td>
												<td>Khaki</td>
												<td>$35290.47</td>
												<td>2017-12-04</td>
												<td align="right">1</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>55648-771</td>
												<td>Buick</td>
												<td>LeSabre</td>
												<td>Violet</td>
												<td>$56243.46</td>
												<td>2016-02-04</td>
												<td align="right">3</td>
												<td align="right">3</td>
											</tr>
											<tr>
												<td>0187-0063</td>
												<td>Mercedes-Benz</td>
												<td>S-Class</td>
												<td>Goldenrod</td>
												<td>$97306.72</td>
												<td>2017-11-06</td>
												<td align="right">5</td>
												<td align="right">3</td>
											</tr>
										</tbody>
									</table>

									<!--end: Datatable -->
								</div>
							</div>
						</div>

						<!-- end:: Content -->
					</div>

					<!-- begin:: Footer -->
					<div class="kt-footer  kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
						<div class="kt-container  kt-container--fluid ">
							<div class="kt-footer__copyright">
								2019&nbsp;&copy;&nbsp;<a href="http://keenthemes.com/metronic" target="_blank" class="kt-link">Keenthemes</a>
							</div>
							<div class="kt-footer__menu">
								<a href="http://keenthemes.com/metronic" target="_blank" class="kt-footer__menu-link kt-link">About</a>
								<a href="http://keenthemes.com/metronic" target="_blank" class="kt-footer__menu-link kt-link">Team</a>
								<a href="http://keenthemes.com/metronic" target="_blank" class="kt-footer__menu-link kt-link">Contact</a>
							</div>
						</div>
					</div>

					<!-- end:: Footer -->
				</div>
			</div>
		</div>

		<!-- end:: Page -->

		<!-- begin::Quick Panel -->
		<div id="kt_quick_panel" class="kt-quick-panel">
			<a href="#" class="kt-quick-panel__close" id="kt_quick_panel_close_btn"><i class="flaticon2-delete"></i></a>
			<div class="kt-quick-panel__nav">
				<ul class="nav nav-tabs nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand  kt-notification-item-padding-x" role="tablist">
					<li class="nav-item active">
						<a class="nav-link active" data-toggle="tab" href="#kt_quick_panel_tab_notifications" role="tab">Notifications</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" data-toggle="tab" href="#kt_quick_panel_tab_logs" role="tab">Audit Logs</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" data-toggle="tab" href="#kt_quick_panel_tab_settings" role="tab">Settings</a>
					</li>
				</ul>
			</div>
			<div class="kt-quick-panel__content">
				<div class="tab-content">
					<div class="tab-pane fade show kt-scroll active" id="kt_quick_panel_tab_notifications" role="tabpanel">
						<div class="kt-notification">
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-line-chart kt-font-success"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New order has been received
									</div>
									<div class="kt-notification__item-time">
										2 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-box-1 kt-font-brand"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New customer is registered
									</div>
									<div class="kt-notification__item-time">
										3 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-chart2 kt-font-danger"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										Application has been approved
									</div>
									<div class="kt-notification__item-time">
										3 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-image-file kt-font-warning"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New file has been uploaded
									</div>
									<div class="kt-notification__item-time">
										5 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-drop kt-font-info"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New user feedback received
									</div>
									<div class="kt-notification__item-time">
										8 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-pie-chart-2 kt-font-success"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										System reboot has been successfully completed
									</div>
									<div class="kt-notification__item-time">
										12 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-favourite kt-font-danger"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New order has been placed
									</div>
									<div class="kt-notification__item-time">
										15 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item kt-notification__item--read">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-safe kt-font-primary"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										Company meeting canceled
									</div>
									<div class="kt-notification__item-time">
										19 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-psd kt-font-success"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New report has been received
									</div>
									<div class="kt-notification__item-time">
										23 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon-download-1 kt-font-danger"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										Finance report has been generated
									</div>
									<div class="kt-notification__item-time">
										25 hrs ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon-security kt-font-warning"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New customer comment recieved
									</div>
									<div class="kt-notification__item-time">
										2 days ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification__item">
								<div class="kt-notification__item-icon">
									<i class="flaticon2-pie-chart kt-font-warning"></i>
								</div>
								<div class="kt-notification__item-details">
									<div class="kt-notification__item-title">
										New customer is registered
									</div>
									<div class="kt-notification__item-time">
										3 days ago
									</div>
								</div>
							</a>
						</div>
					</div>
					<div class="tab-pane fade kt-scroll" id="kt_quick_panel_tab_logs" role="tabpanel">
						<div class="kt-notification-v2">
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon-bell kt-font-brand"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										5 new user generated report
									</div>
									<div class="kt-notification-v2__item-desc">
										Reports based on sales
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon2-box kt-font-danger"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										2 new items submited
									</div>
									<div class="kt-notification-v2__item-desc">
										by Grog John
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon-psd kt-font-brand"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										79 PSD files generated
									</div>
									<div class="kt-notification-v2__item-desc">
										Reports based on sales
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon2-supermarket kt-font-warning"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										$2900 worth producucts sold
									</div>
									<div class="kt-notification-v2__item-desc">
										Total 234 items
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon-paper-plane-1 kt-font-success"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										4.5h-avarage response time
									</div>
									<div class="kt-notification-v2__item-desc">
										Fostest is Barry
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon2-information kt-font-danger"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										Database server is down
									</div>
									<div class="kt-notification-v2__item-desc">
										10 mins ago
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon2-mail-1 kt-font-brand"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										System report has been generated
									</div>
									<div class="kt-notification-v2__item-desc">
										Fostest is Barry
									</div>
								</div>
							</a>
							<a href="#" class="kt-notification-v2__item">
								<div class="kt-notification-v2__item-icon">
									<i class="flaticon2-hangouts-logo kt-font-warning"></i>
								</div>
								<div class="kt-notification-v2__itek-wrapper">
									<div class="kt-notification-v2__item-title">
										4.5h-avarage response time
									</div>
									<div class="kt-notification-v2__item-desc">
										Fostest is Barry
									</div>
								</div>
							</a>
						</div>
					</div>
					<div class="tab-pane kt-quick-panel__content-padding-x fade kt-scroll" id="kt_quick_panel_tab_settings" role="tabpanel">
						<form class="kt-form">
							<div class="kt-heading kt-heading--sm kt-heading--space-sm">Customer Care</div>
							<div class="form-group form-group-xs row">
								<label class="col-8 col-form-label">Enable Notifications:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--success kt-switch--sm">
										<label>
											<input type="checkbox" checked="checked" name="quick_panel_notifications_1">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="form-group form-group-xs row">
								<label class="col-8 col-form-label">Enable Case Tracking:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--success kt-switch--sm">
										<label>
											<input type="checkbox" name="quick_panel_notifications_2">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="form-group form-group-last form-group-xs row">
								<label class="col-8 col-form-label">Support Portal:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--success kt-switch--sm">
										<label>
											<input type="checkbox" checked="checked" name="quick_panel_notifications_2">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="kt-separator kt-separator--space-md kt-separator--border-dashed"></div>
							<div class="kt-heading kt-heading--sm kt-heading--space-sm">Reports</div>
							<div class="form-group form-group-xs row">
								<label class="col-8 col-form-label">Generate Reports:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--sm kt-switch--danger">
										<label>
											<input type="checkbox" checked="checked" name="quick_panel_notifications_3">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="form-group form-group-xs row">
								<label class="col-8 col-form-label">Enable Report Export:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--sm kt-switch--danger">
										<label>
											<input type="checkbox" name="quick_panel_notifications_3">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="form-group form-group-last form-group-xs row">
								<label class="col-8 col-form-label">Allow Data Collection:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--sm kt-switch--danger">
										<label>
											<input type="checkbox" checked="checked" name="quick_panel_notifications_4">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="kt-separator kt-separator--space-md kt-separator--border-dashed"></div>
							<div class="kt-heading kt-heading--sm kt-heading--space-sm">Memebers</div>
							<div class="form-group form-group-xs row">
								<label class="col-8 col-form-label">Enable Member singup:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--sm kt-switch--brand">
										<label>
											<input type="checkbox" checked="checked" name="quick_panel_notifications_5">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="form-group form-group-xs row">
								<label class="col-8 col-form-label">Allow User Feedbacks:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--sm kt-switch--brand">
										<label>
											<input type="checkbox" name="quick_panel_notifications_5">
											<span></span>
										</label>
									</span>
								</div>
							</div>
							<div class="form-group form-group-last form-group-xs row">
								<label class="col-8 col-form-label">Enable Customer Portal:</label>
								<div class="col-4 kt-align-right">
									<span class="kt-switch kt-switch--sm kt-switch--brand">
										<label>
											<input type="checkbox" checked="checked" name="quick_panel_notifications_6">
											<span></span>
										</label>
									</span>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>


		<!-- begin::Global Config(global config for global JS sciprts) -->
		<script>
			var KTAppOptions = {
				"colors": {
					"state": {
						"brand": "#5d78ff",
						"dark": "#282a3c",
						"light": "#ffffff",
						"primary": "#5867dd",
						"success": "#34bfa3",
						"info": "#36a3f7",
						"warning": "#ffb822",
						"danger": "#fd3995"
					},
					"base": {
						"label": [
							"#c5cbe3",
							"#a1a8c3",
							"#3d4465",
							"#3e4466"
						],
						"shape": [
							"#f0f3ff",
							"#d9dffa",
							"#afb4d4",
							"#646c9a"
						]
					}
				}
			};
		</script>

		<!-- end::Global Config -->

		<!--begin::Global Theme Bundle(used by all pages) -->

		<!--begin:: Vendor Plugins -->
		<script src="assets/plugins/general/jquery/dist/jquery.js" type="text/javascript"></script>
		<script src="assets/plugins/general/popper.js/dist/umd/popper.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js-cookie/src/js.cookie.js" type="text/javascript"></script>
		<script src="assets/plugins/general/moment/min/moment.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/tooltip.js/dist/umd/tooltip.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
		<script src="assets/plugins/general/sticky-js/dist/sticky.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/wnumb/wNumb.js" type="text/javascript"></script>
		<script src="assets/plugins/general/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/block-ui/jquery.blockUI.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/bootstrap-datepicker.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/bootstrap-timepicker.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
		<script src="assets/plugins/general/plugins/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/bootstrap-switch.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/select2/dist/js/select2.full.js" type="text/javascript"></script>
		<script src="assets/plugins/general/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
		<script src="assets/plugins/general/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
		<script src="assets/plugins/general/handlebars/dist/handlebars.js" type="text/javascript"></script>
		<script src="assets/plugins/general/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
		<script src="assets/plugins/general/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="assets/plugins/general/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
		<script src="assets/plugins/general/nouislider/distribute/nouislider.js" type="text/javascript"></script>
		<script src="assets/plugins/general/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
		<script src="assets/plugins/general/autosize/dist/autosize.js" type="text/javascript"></script>
		<script src="assets/plugins/general/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/dropzone/dist/dropzone.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/dropzone.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/quill/dist/quill.js" type="text/javascript"></script>
		<script src="assets/plugins/general/@yaireo/tagify/dist/tagify.polyfills.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/@yaireo/tagify/dist/tagify.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/summernote/dist/summernote.js" type="text/javascript"></script>
		<script src="assets/plugins/general/markdown/lib/markdown.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/bootstrap-markdown.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/bootstrap-notify.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
		<script src="assets/plugins/general/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/jquery-validation.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/toastr/build/toastr.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/dual-listbox/dist/dual-listbox.js" type="text/javascript"></script>
		<script src="assets/plugins/general/raphael/raphael.js" type="text/javascript"></script>
		<script src="assets/plugins/general/morris.js/morris.js" type="text/javascript"></script>
		<script src="assets/plugins/general/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
		<script src="assets/plugins/general/plugins/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/plugins/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
		<script src="assets/plugins/general/counterup/jquery.counterup.js" type="text/javascript"></script>
		<script src="assets/plugins/general/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
		<script src="assets/plugins/general/js/global/integration/plugins/sweetalert2.init.js" type="text/javascript"></script>
		<script src="assets/plugins/general/jquery.repeater/src/lib.js" type="text/javascript"></script>
		<script src="assets/plugins/general/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
		<script src="assets/plugins/general/jquery.repeater/src/repeater.js" type="text/javascript"></script>
		<script src="assets/plugins/general/dompurify/dist/purify.js" type="text/javascript"></script>

		<!--end:: Vendor Plugins -->
		<script src="assets/js/scripts.bundle.js" type="text/javascript"></script>

		<!--begin:: Vendor Plugins for custom pages -->
		<script src="assets/plugins/custom/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/@fullcalendar/core/main.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/@fullcalendar/daygrid/main.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/@fullcalendar/google-calendar/main.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/@fullcalendar/interaction/main.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/@fullcalendar/list/main.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/@fullcalendar/timegrid/main.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/gmaps/gmaps.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/dist/es5/jquery.flot.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/source/jquery.flot.resize.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/source/jquery.flot.categories.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/source/jquery.flot.pie.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/source/jquery.flot.stack.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/source/jquery.flot.crosshair.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/flot/source/jquery.flot.axislabels.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-bs4/js/dataTables.bootstrap4.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/js/global/integration/plugins/datatables.init.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-autofill/js/dataTables.autoFill.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-autofill-bs4/js/autoFill.bootstrap4.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jszip/dist/jszip.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/pdfmake/build/pdfmake.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/pdfmake/build/vfs_fonts.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-colreorder/js/dataTables.colReorder.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-fixedcolumns/js/dataTables.fixedColumns.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-keytable/js/dataTables.keyTable.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-rowgroup/js/dataTables.rowGroup.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-rowreorder/js/dataTables.rowReorder.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-scroller/js/dataTables.scroller.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/datatables.net-select/js/dataTables.select.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jstree/dist/jstree.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jqvmap/dist/jquery.vmap.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.world.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.russia.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.usa.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.germany.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.europe.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/uppy/dist/uppy.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/tinymce/tinymce.min.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/tinymce/themes/silver/theme.js" type="text/javascript"></script>
		<script src="assets/plugins/custom/tinymce/themes/mobile/theme.js" type="text/javascript"></script>

		<!--end:: Vendor Plugins for custom pages -->

		<!--end::Global Theme Bundle -->

		<!--begin::Page Vendors(used by this page) -->
		<script src="//maps.google.com/maps/api/js?key=AIzaSyBTGnKT7dt597vo9QgeQ7BFhvSRP4eiMSM" type="text/javascript"></script>

		<!--end::Page Vendors -->

		<!--begin::Page Scripts(used by this page) -->
		<script src="assets/js/pages/dashboard.js" type="text/javascript"></script>
		<script src="assets/js/pages/crud/metronic-datatable/base/html-table.js" type="text/javascript"></script>


		<!--end::Page Scripts -->
	</body>

	<!-- end::Body -->
</html>