
					<!-- begin:: Footer -->
					<div class="kt-footer  kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
						<div class="kt-container  kt-container--fluid ">
							<div class="kt-footer__copyright">
								2022&nbsp;&copy;&nbsp;<a href="https://www.fanatics.com/" target="_blank" class="kt-link">Fanatics</a>
							</div>
							<div class="kt-footer__menu">
								<a href="http://fanatics.com/why-shop-with-us/ch-2389" target="_blank" class="kt-footer__menu-link kt-link">About</a>
								<a href="https://www.fanatics.com/customer-help-desk/hd-1" target="_blank" class="kt-footer__menu-link kt-link">Help</a>
								<a href="https://www.fanatics.com/how-can-i-contact-customer-service/ch-2241" target="_blank" class="kt-footer__menu-link kt-link">Contact</a>
							</div>
						</div>
					</div>
					<!-- end:: Footer -->
				</div>
			</div>

		</div>
	</div>


	<!-- end:: Page -->


	<!-- begin::Quick Panel -->
	<div id="kt_quick_panel" class="kt-quick-panel">
		<a href="#" class="kt-quick-panel__close" id="kt_quick_panel_close_btn"><i class="flaticon2-delete"></i></a>
		<div class="kt-quick-panel__nav">
			<ul class="nav nav-tabs nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand  kt-notification-item-padding-x" role="tablist">
				<li class="nav-item active">
					<a class="nav-link active" data-toggle="tab" href="#kt_quick_panel_tab_notifications" role="tab">Notifications</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" data-toggle="tab" href="#kt_quick_panel_tab_logs" role="tab">Audit Logs</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" data-toggle="tab" href="#kt_quick_panel_tab_settings" role="tab">Settings</a>
				</li>
			</ul>
		</div>
		<div class="kt-quick-panel__content">
			<div class="tab-content">
				<div class="tab-pane fade show kt-scroll active" id="kt_quick_panel_tab_notifications" role="tabpanel">
					<div class="kt-notification">
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-line-chart kt-font-success"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New order has been received
								</div>
								<div class="kt-notification__item-time">
									2 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-box-1 kt-font-brand"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New customer is registered
								</div>
								<div class="kt-notification__item-time">
									3 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-chart2 kt-font-danger"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									Application has been approved
								</div>
								<div class="kt-notification__item-time">
									3 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-image-file kt-font-warning"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New file has been uploaded
								</div>
								<div class="kt-notification__item-time">
									5 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-drop kt-font-info"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New user feedback received
								</div>
								<div class="kt-notification__item-time">
									8 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-pie-chart-2 kt-font-success"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									System reboot has been successfully completed
								</div>
								<div class="kt-notification__item-time">
									12 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-favourite kt-font-danger"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New order has been placed
								</div>
								<div class="kt-notification__item-time">
									15 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item kt-notification__item--read">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-safe kt-font-primary"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									Company meeting canceled
								</div>
								<div class="kt-notification__item-time">
									19 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-psd kt-font-success"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New report has been received
								</div>
								<div class="kt-notification__item-time">
									23 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon-download-1 kt-font-danger"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									Finance report has been generated
								</div>
								<div class="kt-notification__item-time">
									25 hrs ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon-security kt-font-warning"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New customer comment recieved
								</div>
								<div class="kt-notification__item-time">
									2 days ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification__item">
							<div class="kt-notification__item-icon">
								<i class="flaticon2-pie-chart kt-font-warning"></i>
							</div>
							<div class="kt-notification__item-details">
								<div class="kt-notification__item-title">
									New customer is registered
								</div>
								<div class="kt-notification__item-time">
									3 days ago
								</div>
							</div>
						</a>
					</div>
				</div>
				<div class="tab-pane fade kt-scroll" id="kt_quick_panel_tab_logs" role="tabpanel">
					<div class="kt-notification-v2">
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon-bell kt-font-brand"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									5 new user generated report
								</div>
								<div class="kt-notification-v2__item-desc">
									Reports based on sales
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon2-box kt-font-danger"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									2 new items submited
								</div>
								<div class="kt-notification-v2__item-desc">
									by Grog John
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon-psd kt-font-brand"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									79 PSD files generated
								</div>
								<div class="kt-notification-v2__item-desc">
									Reports based on sales
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon2-supermarket kt-font-warning"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									$2900 worth producucts sold
								</div>
								<div class="kt-notification-v2__item-desc">
									Total 234 items
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon-paper-plane-1 kt-font-success"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									4.5h-avarage response time
								</div>
								<div class="kt-notification-v2__item-desc">
									Fostest is Barry
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon2-information kt-font-danger"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									Database server is down
								</div>
								<div class="kt-notification-v2__item-desc">
									10 mins ago
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon2-mail-1 kt-font-brand"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									System report has been generated
								</div>
								<div class="kt-notification-v2__item-desc">
									Fostest is Barry
								</div>
							</div>
						</a>
						<a href="#" class="kt-notification-v2__item">
							<div class="kt-notification-v2__item-icon">
								<i class="flaticon2-hangouts-logo kt-font-warning"></i>
							</div>
							<div class="kt-notification-v2__itek-wrapper">
								<div class="kt-notification-v2__item-title">
									4.5h-avarage response time
								</div>
								<div class="kt-notification-v2__item-desc">
									Fostest is Barry
								</div>
							</div>
						</a>
					</div>
				</div>
				<div class="tab-pane kt-quick-panel__content-padding-x fade kt-scroll" id="kt_quick_panel_tab_settings" role="tabpanel">
					<form class="kt-form">
						<div class="kt-heading kt-heading--sm kt-heading--space-sm">Customer Care</div>
						<div class="form-group form-group-xs row">
							<label class="col-8 col-form-label">Enable Notifications:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--success kt-switch--sm">
									<label>
										<input type="checkbox" checked="checked" name="quick_panel_notifications_1">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="form-group form-group-xs row">
							<label class="col-8 col-form-label">Enable Case Tracking:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--success kt-switch--sm">
									<label>
										<input type="checkbox" name="quick_panel_notifications_2">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="form-group form-group-last form-group-xs row">
							<label class="col-8 col-form-label">Support Portal:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--success kt-switch--sm">
									<label>
										<input type="checkbox" checked="checked" name="quick_panel_notifications_2">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="kt-separator kt-separator--space-md kt-separator--border-dashed"></div>
						<div class="kt-heading kt-heading--sm kt-heading--space-sm">Reports</div>
						<div class="form-group form-group-xs row">
							<label class="col-8 col-form-label">Generate Reports:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--sm kt-switch--danger">
									<label>
										<input type="checkbox" checked="checked" name="quick_panel_notifications_3">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="form-group form-group-xs row">
							<label class="col-8 col-form-label">Enable Report Export:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--sm kt-switch--danger">
									<label>
										<input type="checkbox" name="quick_panel_notifications_3">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="form-group form-group-last form-group-xs row">
							<label class="col-8 col-form-label">Allow Data Collection:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--sm kt-switch--danger">
									<label>
										<input type="checkbox" checked="checked" name="quick_panel_notifications_4">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="kt-separator kt-separator--space-md kt-separator--border-dashed"></div>
						<div class="kt-heading kt-heading--sm kt-heading--space-sm">Memebers</div>
						<div class="form-group form-group-xs row">
							<label class="col-8 col-form-label">Enable Member singup:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--sm kt-switch--brand">
									<label>
										<input type="checkbox" checked="checked" name="quick_panel_notifications_5">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="form-group form-group-xs row">
							<label class="col-8 col-form-label">Allow User Feedbacks:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--sm kt-switch--brand">
									<label>
										<input type="checkbox" name="quick_panel_notifications_5">
										<span></span>
									</label>
								</span>
							</div>
						</div>
						<div class="form-group form-group-last form-group-xs row">
							<label class="col-8 col-form-label">Enable Customer Portal:</label>
							<div class="col-4 kt-align-right">
								<span class="kt-switch kt-switch--sm kt-switch--brand">
									<label>
										<input type="checkbox" checked="checked" name="quick_panel_notifications_6">
										<span></span>
									</label>
								</span>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- end::Quick Panel -->






	<!-- SCRIPTS STARTING FROM HERE  -->
	<!-- begin::Global Config(global config for global JS sciprts) -->
	<script>
		var KTAppOptions = {
			"colors": {
				"state": {
					"brand": "#5d78ff",
					"dark": "#282a3c",
					"light": "#ffffff",
					"primary": "#5867dd",
					"success": "#34bfa3",
					"info": "#36a3f7",
					"warning": "#ffb822",
					"danger": "#fd3995"
				},
				"base": {
					"label": [
						"#c5cbe3",
						"#a1a8c3",
						"#3d4465",
						"#3e4466"
					],
					"shape": [
						"#f0f3ff",
						"#d9dffa",
						"#afb4d4",
						"#646c9a"
					]
				}
			}
		};
	</script>
	<!-- end::Global Config -->

	<!--begin::Global Theme Bundle(used by all pages) -->

	<!--begin:: Vendor Plugins -->
	<script src="../assets/plugins/general/jquery/dist/jquery.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/popper.js/dist/umd/popper.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js-cookie/src/js.cookie.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/moment/min/moment.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/tooltip.js/dist/umd/tooltip.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/sticky-js/dist/sticky.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/wnumb/wNumb.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/block-ui/jquery.blockUI.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/bootstrap-datepicker.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/bootstrap-timepicker.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/plugins/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-select/dist/js/bootstrap-select.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-switch/dist/js/bootstrap-switch.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/bootstrap-switch.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/select2/dist/js/select2.full.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/typeahead.js/dist/typeahead.bundle.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/handlebars/dist/handlebars.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/inputmask/dist/jquery.inputmask.bundle.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/inputmask/dist/inputmask/inputmask.date.extensions.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/inputmask/dist/inputmask/inputmask.numeric.extensions.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/nouislider/distribute/nouislider.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/owl.carousel/dist/owl.carousel.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/autosize/dist/autosize.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/clipboard/dist/clipboard.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/dropzone/dist/dropzone.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/dropzone.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/quill/dist/quill.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/@yaireo/tagify/dist/tagify.polyfills.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/@yaireo/tagify/dist/tagify.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/summernote/dist/summernote.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/markdown/lib/markdown.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/bootstrap-markdown.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/bootstrap-notify/bootstrap-notify.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/bootstrap-notify.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/jquery-validation.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/toastr/build/toastr.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/dual-listbox/dist/dual-listbox.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/raphael/raphael.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/morris.js/morris.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/plugins/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/plugins/jquery-idletimer/idle-timer.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/waypoints/lib/jquery.waypoints.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/counterup/jquery.counterup.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/es6-promise-polyfill/promise.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/js/global/integration/plugins/sweetalert2.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/jquery.repeater/src/lib.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/jquery.repeater/src/repeater.js" type="text/javascript"></script>
	<script src="../assets/plugins/general/dompurify/dist/purify.js" type="text/javascript"></script>

	<!--end:: Vendor Plugins -->
	<script src="../assets/js/scripts.bundle.js" type="text/javascript"></script>

	<!--begin:: Vendor Plugins for custom pages -->
	<script src="../assets/plugins/custom/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/@fullcalendar/core/main.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/@fullcalendar/daygrid/main.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/@fullcalendar/google-calendar/main.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/@fullcalendar/interaction/main.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/@fullcalendar/list/main.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/@fullcalendar/timegrid/main.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/gmaps/gmaps.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/dist/es5/jquery.flot.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/source/jquery.flot.resize.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/source/jquery.flot.categories.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/source/jquery.flot.pie.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/source/jquery.flot.stack.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/source/jquery.flot.crosshair.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/flot/source/jquery.flot.axislabels.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-bs4/js/dataTables.bootstrap4.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/js/global/integration/plugins/datatables.init.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-autofill/js/dataTables.autoFill.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-autofill-bs4/js/autoFill.bootstrap4.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jszip/dist/jszip.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/pdfmake/build/pdfmake.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/pdfmake/build/vfs_fonts.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-buttons/js/buttons.colVis.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-buttons/js/buttons.flash.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-buttons/js/buttons.html5.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-buttons/js/buttons.print.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-colreorder/js/dataTables.colReorder.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-fixedcolumns/js/dataTables.fixedColumns.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-keytable/js/dataTables.keyTable.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-rowgroup/js/dataTables.rowGroup.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-rowreorder/js/dataTables.rowReorder.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-scroller/js/dataTables.scroller.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/datatables.net-select/js/dataTables.select.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jstree/dist/jstree.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jqvmap/dist/jquery.vmap.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.world.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.russia.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.usa.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.germany.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/jqvmap/dist/maps/jquery.vmap.europe.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/uppy/dist/uppy.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/tinymce/tinymce.min.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/tinymce/themes/silver/theme.js" type="text/javascript"></script>
	<script src="../assets/plugins/custom/tinymce/themes/mobile/theme.js" type="text/javascript"></script>

	<!--end:: Vendor Plugins for custom pages -->

	<!--end::Global Theme Bundle -->

	<!--begin::Page Vendors(used by this page) -->
	<script src="//maps.google.com/maps/api/js?key=AIzaSyBTGnKT7dt597vo9QgeQ7BFhvSRP4eiMSM" type="text/javascript"></script>

	<!--end::Page Vendors -->

	<!--begin::Page Scripts(used by this page) -->
	<script src="../assets/js/pages/dashboard.js" type="text/javascript"></script>
	<script src="../assets/js/pages/crud/metronic-datatable/base/html-table.js" type="text/javascript"></script>
	<script src="../assets/js/pages/custom/user/edit-user.js" type="text/javascript"></script>
	<script src="../assets/js/productmodel.js" type="text/javascript"></script>

	<!--end::Page Scripts -->



</body>

<!-- end::Body -->

</html>